name: a2l
description: A library that can read and write ASAP2 (A2L) files. This an automotive standard for measurement and calibration data definitions (ASAM MCD-2MC).
version: 0.5.0
homepage: https://github.com/domohuhn/a2l
repository: https://github.com/domohuhn/a2l

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  mutation_test: ^1.2.1
  test: ^1.16.0
